# Generated by Django 3.1 on 2020-08-28 02:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0002_auto_20200828_0247'),
    ]

    operations = [
        migrations.CreateModel(
            name='Stack',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
            ],
        ),
        migrations.RemoveField(
            model_name='project',
            name='stack',
        ),
        migrations.RemoveField(
            model_name='job',
            name='stack',
        ),
        migrations.AddField(
            model_name='job',
            name='stack',
            field=models.ManyToManyField(to='jobs.Stack'),
        ),
    ]
