# Generated by Django 3.1 on 2020-08-28 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0003_auto_20200828_0248'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='image',
        ),
        migrations.AddField(
            model_name='project',
            name='stack',
            field=models.ManyToManyField(to='jobs.Stack'),
        ),
        migrations.AlterField(
            model_name='project',
            name='liveURL',
            field=models.URLField(default=None),
        ),
    ]
