# Generated by Django 3.1 on 2020-08-28 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0005_project_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='isLive',
            field=models.BooleanField(default=False),
        ),
    ]
